version: "3"
services:
  nest-desktop:
    build: nest-desktop
    container_name: "nest-desktop"
    ports:
      - "8000:8000"

  nest-simulator:
    build: nest-simulator
    container_name: "nest-simulator"
    ports:
      - "5000:5000"
