version: "3"

services:
  nest-desktop:
    image: docker-registry.ebrains.eu/nest/nest-desktop:3.1
    ports:
      - 8000:8000

  nest-simulator:
    image: docker-registry.ebrains.eu/nest/nest-simulator:3.3
    environment:
      NEST_CONTAINER_MODE: nest-server
      NEST_SERVER_HOST: 0.0.0.0
      NEST_SERVER_MODULES: nest,numpy
      NEST_SERVER_PORT: 5000
      NEST_SERVER_RESTRICTION_OFF: 1
    ports:
      - 5000:5000
