version: "3"

services:
  build-nest-desktop:
    build: ./nest-desktop
    ports:
      - "8000:8000"

  build-nest-simulator:
    build: ./nest-simulator
    environment:
      NEST_CONTAINER_MODE: "nest-server"
      NEST_SERVER_BUFFER_SIZE: 65535
      NEST_SERVER_HOST: "0.0.0.0"
      NEST_SERVER_MODULES: "nest,numpy"
      NEST_SERVER_PORT: 5000
      NEST_SERVER_RESTRICTION_OFF: 1
    ports:
      - "5000:5000"
