version: "3"

services:

  nest-desktop:
    image: docker-registry.ebrains.eu/nest/nest-simulator:3.4
    environment:
      NEST_CONTAINER_MODE: "nest-desktop"
      NEST_SIMULATOR_PORT: 54321
    ports:
      - "54286:54286"

  nest-server:
    image: docker-registry.ebrains.eu/nest/nest-simulator:3.4
    environment:
      NEST_CONTAINER_MODE: "nest-server"
      NEST_SERVER_PORT: 54321
    ports:
      - "54321:54321"
